### ISSUE TITLE
can't run with nexus 71

### ISSUE THREAD

**Issue by sample** [805728578/nexus-repository-apk#6]
* **What are you trying to do?**
Trying to build and run nexus-repository-apk with nexus 3.71

* **What feature or behavior is this required for?**
Nexus should run with nexus-repository-apk plugin installed. It's builds and starts successfully, but when i'm trying to access nexus ui, there is an error:
`nexus3-nexus-1  | 2024-08-29 20:42:35,625+0000 WARN  [qtp2108327868-604] *UNKNOWN org.sonatype.nexus.rapture.internal.state.StateComponent - Failed to get state from com.google.inject.internal.InjectorImpl$1 (ignored)
nexus3-nexus-1  | com.google.inject.ProvisionException: Unable to provision, see the following errors:
nexus3-nexus-1  |
nexus3-nexus-1  | 1) [Guice/ErrorInjectingConstructor]: GroovyRuntimeException: Could not find matching constructor for: ApkRecipeSupport(ProxyType, ApkFormat)
nexus3-nexus-1  |   at ApkProxyRecipe.<init>(ApkProxyRecipe.groovy:63)
nexus3-nexus-1  |   at /
nexus3-nexus-1  |       \_ installed by: NexusBundleModule -> SpaceModule
nexus3-nexus-1  |   while locating ApkProxyRecipe
nexus3-nexus-1  |   while locating Object annotated with *
nexus3-nexus-1  |   at /
nexus3-nexus-1  |       \_ installed by: NexusBundleModule -> SpaceModule
nexus3-nexus-1  |   while locating RepositoryUiService
nexus3-nexus-1  |   while locating Object annotated with *
nexus3-nexus-1  |
nexus3-nexus-1  | Learn more:
nexus3-nexus-1  |   https://github.com/google/guice/wiki/ERROR_INJECTING_CONSTRUCTOR
nexus3-nexus-1  |
nexus3-nexus-1  | 1 error
nexus3-nexus-1  |
nexus3-nexus-1  | ======================
nexus3-nexus-1  | Full classname legend:
nexus3-nexus-1  | ======================
nexus3-nexus-1  | ApkFormat:              "org.sonatype.nexus.plugins.apk.internal.ApkFormat"
nexus3-nexus-1  | ApkProxyRecipe:         "org.sonatype.nexus.plugins.apk.datastore.internal.ApkProxyRecipe"
nexus3-nexus-1  | ApkRecipeSupport:       "org.sonatype.nexus.plugins.apk.datastore.internal.ApkRecipeSupport"
nexus3-nexus-1  | GroovyRuntimeException: "groovy.lang.GroovyRuntimeException"
nexus3-nexus-1  | NexusBundleModule:      "org.sonatype.nexus.extender.modules.NexusBundleModule"
nexus3-nexus-1  | ProxyType:              "org.sonatype.nexus.repository.types.ProxyType"
nexus3-nexus-1  | RepositoryUiService:    "org.sonatype.nexus.coreui.service.RepositoryUiService"
nexus3-nexus-1  | SpaceModule:            "org.eclipse.sisu.space.SpaceModule"
nexus3-nexus-1  | ========================
nexus3-nexus-1  | End of classname legend:
nexus3-nexus-1  | ========================
nexus3-nexus-1  |
nexus3-nexus-1  | 	at com.google.inject.internal.InternalProvisionException.toProvisionException(InternalProvisionException.java:251)
nexus3-nexus-1  | 	at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1151)
nexus3-nexus-1  | 	at org.sonatype.nexus.rapture.internal.state.StateComponent.getState(StateComponent.java:87)
nexus3-nexus-1  | 	at org.sonatype.nexus.rapture.internal.state.StateComponent$$EnhancerByGuice$$147d92da.GUICE$TRAMPOLINE(<generated>)
nexus3-nexus-1  | 	at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:74)
nexus3-nexus-1  | 	at com.palominolabs.metrics.guice.ExceptionMeteredInterceptor.invoke(ExceptionMeteredInterceptor.java:23)
nexus3-nexus-1  | 	at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:75)
nexus3-nexus-1  | 	at com.palominolabs.metrics.guice.TimedInterceptor.invoke(TimedInterceptor.java:26)
nexus3-nexus-1  | 	at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:75)
nexus3-nexus-1  | 	at com.google.inject.internal.InterceptorStackCallback.invoke(InterceptorStackCallback.java:55)
nexus3-nexus-1  | 	at org.sonatype.nexus.rapture.internal.state.StateComponent$$EnhancerByGuice$$147d92da.getState(<generated>)
nexus3-nexus-1  | 	at org.sonatype.nexus.rapture.internal.RaptureWebResourceBundle.getState(RaptureWebResourceBundle.java:348)
nexus3-nexus-1  | 	at org.sonatype.nexus.rapture.internal.RaptureWebResourceBundle.access$6(RaptureWebResourceBundle.java:347)
nexus3-nexus-1  | 	at org.sonatype.nexus.rapture.internal.RaptureWebResourceBundle$5.generate(RaptureWebResourceBundle.java:305)
nexus3-nexus-1  | 	at org.sonatype.nexus.webresources.GeneratedWebResource$1.<init>(GeneratedWebResource.java:63)
nexus3-nexus-1  | 	at org.sonatype.nexus.webresources.GeneratedWebResource.prepare(GeneratedWebResource.java:58)
nexus3-nexus-1  | 	at org.sonatype.nexus.internal.webresources.WebResourceServlet.serveResource(WebResourceServlet.java:128)
nexus3-nexus-1  | 	at org.sonatype.nexus.internal.webresources.WebResourceServlet.doGet(WebResourceServlet.java:112)
nexus3-nexus-1  | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
nexus3-nexus-1  | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
nexus3-nexus-1  | 	at com.google.inject.servlet.ServletDefinition.doServiceImpl(ServletDefinition.java:293)
nexus3-nexus-1  | 	at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:283)
nexus3-nexus-1  | 	at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:184)
nexus3-nexus-1  | 	at com.google.inject.servlet.DynamicServletPipeline.service(DynamicServletPipeline.java:71)
nexus3-nexus-1  | 	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:85)
nexus3-nexus-1  | 	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:61)
nexus3-nexus-1  | 	at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108)
nexus3-nexus-1  | 	at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137)
nexus3-nexus-1  | 	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:154)
nexus3-nexus-1  | 	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66)
nexus3-nexus-1  | 	at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108)
nexus3-nexus-1  | 	at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137)
nexus3-nexus-1  | 	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:154)
nexus3-nexus-1  | 	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66)
nexus3-nexus-1  | 	at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:458)
nexus3-nexus-1  | 	at org.sonatype.nexus.security.SecurityFilter.executeChain(SecurityFilter.java:96)
nexus3-nexus-1  | 	at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:373)
nexus3-nexus-1  | 	at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
nexus3-nexus-1  | 	at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
nexus3-nexus-1  | 	at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:387)
nexus3-nexus-1  | 	at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:370)
nexus3-nexus-1  | 	at org.sonatype.nexus.security.SecurityFilter.doFilterInternal(SecurityFilter.java:112)
nexus3-nexus-1  | 	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:154)
nexus3-nexus-1  | 	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
nexus3-nexus-1  | 	at com.codahale.metrics.servlet.AbstractInstrumentedFilter.doFilter(AbstractInstrumentedFilter.java:112)
nexus3-nexus-1  | 	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
nexus3-nexus-1  | 	at com.sonatype.nexus.licensing.internal.LicensingRedirectFilter.doFilter(LicensingRedirectFilter.java:116)
nexus3-nexus-1  | 	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
nexus3-nexus-1  | 	at com.codahale.metrics.servlet.AbstractInstrumentedFilter.doFilter(AbstractInstrumentedFilter.java:112)
nexus3-nexus-1  | 	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
nexus3-nexus-1  | 	at org.sonatype.nexus.internal.web.ErrorPageFilter.doFilter(ErrorPageFilter.java:79)
nexus3-nexus-1  | 	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
nexus3-nexus-1  | 	at org.sonatype.nexus.internal.web.EnvironmentFilter.doFilter(EnvironmentFilter.java:101)
nexus3-nexus-1  | 	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
nexus3-nexus-1  | 	at org.sonatype.nexus.internal.web.HeaderPatternFilter.doFilter(HeaderPatternFilter.java:98)
nexus3-nexus-1  | 	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
nexus3-nexus-1  | 	at com.google.inject.servlet.DynamicFilterPipeline.dispatch(DynamicFilterPipeline.java:104)
nexus3-nexus-1  | 	at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:133)
nexus3-nexus-1  | 	at org.sonatype.nexus.bootstrap.osgi.DelegatingFilter.doFilter(DelegatingFilter.java:73)
nexus3-nexus-1  | 	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:201)
nexus3-nexus-1  | 	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1626)
nexus3-nexus-1  | 	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:552)
nexus3-nexus-1  | 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
nexus3-nexus-1  | 	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:600)
nexus3-nexus-1  | 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
nexus3-nexus-1  | 	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)
nexus3-nexus-1  | 	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1624)
nexus3-nexus-1  | 	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
nexus3-nexus-1  | 	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1440)
nexus3-nexus-1  | 	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
nexus3-nexus-1  | 	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:505)
nexus3-nexus-1  | 	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1594)
nexus3-nexus-1  | 	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
nexus3-nexus-1  | 	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1355)
nexus3-nexus-1  | 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
nexus3-nexus-1  | 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
nexus3-nexus-1  | 	at com.codahale.metrics.jetty9.InstrumentedHandler.handle(InstrumentedHandler.java:239)
nexus3-nexus-1  | 	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146)
nexus3-nexus-1  | 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
nexus3-nexus-1  | 	at org.eclipse.jetty.server.Server.handle(Server.java:516)
nexus3-nexus-1  | 	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:487)
nexus3-nexus-1  | 	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:732)
nexus3-nexus-1  | 	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:479)
nexus3-nexus-1  | 	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
nexus3-nexus-1  | 	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
nexus3-nexus-1  | 	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
nexus3-nexus-1  | 	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
nexus3-nexus-1  | 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338)
nexus3-nexus-1  | 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315)
nexus3-nexus-1  | 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)
nexus3-nexus-1  | 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
nexus3-nexus-1  | 	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:409)
nexus3-nexus-1  | 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
nexus3-nexus-1  | 	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
nexus3-nexus-1  | 	at java.base/java.lang.Thread.run(Thread.java:840)
nexus3-nexus-1  | Caused by: groovy.lang.GroovyRuntimeException: Could not find matching constructor for: org.sonatype.nexus.plugins.apk.datastore.internal.ApkRecipeSupport(org.sonatype.nexus.repository.types.ProxyType, org.sonatype.nexus.plugins.apk.internal.ApkFormat)
nexus3-nexus-1  | 	at groovy.lang.MetaClassImpl.createCachedConstructor(MetaClassImpl.java:1653)
nexus3-nexus-1  | 	at groovy.lang.MetaClassImpl.selectConstructorAndTransformArguments1(MetaClassImpl.java:1679)
nexus3-nexus-1  | 	at groovy.lang.MetaClassImpl.selectConstructorAndTransformArguments(MetaClassImpl.java:1606)
nexus3-nexus-1  | 	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.selectConstructorAndTransformArguments(ScriptBytecodeAdapter.java:250)
nexus3-nexus-1  | 	at org.sonatype.nexus.plugins.apk.datastore.internal.ApkProxyRecipe.<init>(ApkProxyRecipe.groovy:63)
nexus3-nexus-1  | 	at org.sonatype.nexus.plugins.apk.datastore.internal.ApkProxyRecipe$$FastClassByGuice$$ffffffff83ee462c.GUICE$TRAMPOLINE(<generated>)
nexus3-nexus-1  | 	at org.sonatype.nexus.plugins.apk.datastore.internal.ApkProxyRecipe$$FastClassByGuice$$ffffffff83ee462c.apply(<generated>)
nexus3-nexus-1  | 	at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:82)
nexus3-nexus-1  | 	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114)
nexus3-nexus-1  | 	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91)
nexus3-nexus-1  | 	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:300)
nexus3-nexus-1  | 	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
nexus3-nexus-1  | 	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:169)
nexus3-nexus-1  | 	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45)
nexus3-nexus-1  | 	at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:60)
nexus3-nexus-1  | 	at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1148)
nexus3-nexus-1  | 	at org.eclipse.sisu.inject.LazyBeanEntry.getValue(LazyBeanEntry.java:81)
nexus3-nexus-1  | 	at org.eclipse.sisu.wire.NamedIterableAdapter$NamedEntry.getValue(NamedIterableAdapter.java:125)
nexus3-nexus-1  | 	at java.base/java.util.HashMap.putMapEntries(HashMap.java:513)
nexus3-nexus-1  | 	at java.base/java.util.HashMap.<init>(HashMap.java:484)
nexus3-nexus-1  | 	at org.sonatype.nexus.coreui.service.RepositoryUiService.<init>(RepositoryUiService.java:129)
nexus3-nexus-1  | 	at org.sonatype.nexus.coreui.service.RepositoryUiService$$EnhancerByGuice$$2a9226c0.<init>(<generated>)
nexus3-nexus-1  | 	at org.sonatype.nexus.coreui.service.RepositoryUiService$$EnhancerByGuice$$2a9226c0.GUICE$TRAMPOLINE(<generated>)
nexus3-nexus-1  | 	at com.google.inject.internal.ProxyFactory$ProxyConstructor.newInstance(ProxyFactory.java:183)
nexus3-nexus-1  | 	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114)
nexus3-nexus-1  | 	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91)
nexus3-nexus-1  | 	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:300)
nexus3-nexus-1  | 	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
nexus3-nexus-1  | 	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:169)
nexus3-nexus-1  | 	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45)
nexus3-nexus-1  | 	at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:60)
nexus3-nexus-1  | 	at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1148)
nexus3-nexus-1  | 	... 93 common frames omitted`

* **How could we solve this issue? (Not knowing is okay!)**
don't know, maybe fix constructor for: ApkRecipeSupport

cc @DarthHater @bhamail

**Comment by Spanish93** [comment]
Same problem here, but the problem is not nexus 3.71 but the database, plugin it's working with 3.70 with OrientDB, but not working after migration to H2. (and nexus 3.71 need H2 also) @805728578 @bhamail @DarthHater 

edit : it's seems that code under orient it's working, but code in datastore is not working :(
So no support for H2 and nexus 3.71+

**Comment by jearton** [comment]
Any update?
